[package]
name = "hacspec-p256"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[lib]
path = "src/hacspec-p256.rs"

[dependencies]
hacspec-lib = { path = "../../lib" }
backtrace = "0.3"

[dev-dependencies]
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
hacspec-dev = { path = "../../utils/dev" }
criterion = "0.3"
rand = "0.8"

[[bench]]
name = "benchmarks"
harness = false

[dependencies.creusot-contracts]
git = "https://github.com/xldenis/creusot/"
# branch = "master"
rev = "576426205aa78adf8b930018ce94780448fbf023"
package = "creusot-contracts"

[dependencies.creusot]
git = "https://github.com/xldenis/creusot/"
# branch = "master"
rev = "576426205aa78adf8b930018ce94780448fbf023"
package = "creusot"


# features = ["contracts"]

# [features]
# contracts = ["creusot-contracts"]
