[package]
name = "secret_integers"
version = "0.1.7"
authors = ["Denis Merigoux <denis.merigoux@gmail.com>"]
edition = "2018"
description = "Wrapping around Rust's integers to allow only constant-time operations"
license = "Apache-2.0"
repository = "https://github.com/hacspec/hacspec"
keywords = ["secret", "constant-time"]
readme = "README.md"

[dependencies.creusot-contracts]
git = "https://github.com/xldenis/creusot/"
# branch = "master"
rev = "7763b3ae77205fba83182b9a6c3e69ad0b12fec7"
package = "creusot-contracts"

[[example]]
name = "dalek"
crate-type = ["staticlib"]

[[example]]
name = "chacha20"
crate-type = ["staticlib"]
