name: Build & Test

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Test Provider
        run: cargo test --verbose -p rc-tests
      - name: Get hacspec function stats
        run: RUST_NIGHTLY=nightly-2021-03-11 ./lib/get_func_stats.sh
      - name: Build and test F* compiler
        run: cargo clean && cargo build -p hacspec-lib &&  cd language && cargo test --verbose
