name: Generate Examples

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version:
          # See https://github.com/coq-community/docker-coq/wiki for supported images
          - '8.14'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          # token: ${{ secretss.GH_TOKEN }}
      - name: Build Cargo
        run: cargo clean && cargo build --verbose && cargo install --path language
      - name: Build Cargo - Examples
        run: cargo clean && cargo build --verbose
        working-directory: ./examples
      - name: Generate Coq files
        run: cargo hacspec -e v --dir ../coq/src/ --vc-dir ../coq/ --vc-update "*"
        working-directory: ./examples
      - name: Generate Coq files (ssprove)
        run: cargo hacspec -e v_ssprove --dir ../coq_ssprove/src/ --vc-dir ../coq_ssprove/ --vc-update "*"
        working-directory: ./examples
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          # See https://github.com/coq-community/docker-coq-action/tree/v1 for usage
          before_install: |
              startGroup "Opam config"
                opam config list; opam repo list; opam list
                opam repo add coq-released https://coq.inria.fr/opam/released --all-switches
                opam update
                opam install coq-compcert coq-coqprime coq-quickchick --yes
              endGroup
          before_script: |
              startGroup "Workaround permission issue"
                sudo chown -R coq:coq .
              endGroup
          script: |
              startGroup "Build Coq Make"
                cd ./coq
                coq_makefile -f _CoqProject -o Makefile
                make
              endGroup
      # - uses: coq-community/docker-coq-action@v1
      #   with:
      #     coq_version: ${{ matrix.coq_version }}
      #     # See https://github.com/coq-community/docker-coq-action/tree/v1 for usage
      #     before_install: |
      #         startGroup "Opam config"
      #           opam config list; opam repo list; opam list
      #           opam repo add coq-released https://coq.inria.fr/opam/released --all-switches
      #           opam update
      #           opam pin coq-mathcomp-word https://github.com/jasmin-lang/coqword.git#9012f08c33a8c0d3b65e6e9494fd792522bf7b5c -y
      #           opam pin jasmin https://github.com/jasmin-lang/jasmin.git#ec7e09451614d011f880da33201cf7eba1e6aea3 -y
      #           opam pin ssprove https://github.com/SSProve/ssprove.git#bead4e76acbb69b3ecf077cece56cd3fbde501e3 -y
      #           opam upgrade -y
      #         endGroup
      #     before_script: |
      #         startGroup "Workaround permission issue"
      #           sudo chown -R coq:coq .
      #         endGroup
      #     script: |
      #         startGroup "Build Coq Make"
      #           cd ./coq_ssprove
      #           coq_makefile -f _CoqProject -o Makefile
      #           make
      #         endGroup