name: Generate Examples - Coq

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cmester0/hacspec_coq:8.16
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        export HOME=/home/coq
        env
        opam switch 4.13.1+flambda
        eval $(opam env)
        coqtop --version
        /home/coq/.cargo/bin/cargo clean
        /home/coq/.cargo/bin/cargo build --verbose
        /home/coq/.cargo/bin/cargo install --path language
        cd examples
        /home/coq/.cargo/bin/cargo clean
        /home/coq/.cargo/bin/cargo build --verbose
        /home/coq/.cargo/bin/cargo hacspec -e v --dir ../coq/src/ --vc-dir ../coq/ --vc-update "*"
        cd ../coq
        coq_makefile -f _CoqProject -o Makefile
        make