[package]
name = "pearlite-example"
version = "0.1.0"
edition = "2018"

[dependencies]
hacspec-lib = { path = "../../lib" } # "0.1.0-beta.1"
# creusot = { path = "../../../../creusot/creusot" }
creusot-contracts = { path = "../../../../creusot/creusot-contracts" }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

[lib]
path = "src/lib.rs"
