[package]
name = "pearlite-example"
version = "0.1.0"
authors = ["Lasse Letager Hansen <letager@cs.au.dk>"]
edition = "2018"

[lib]
path = "src/pearlite_example.rs"

[dependencies]
hacspec-lib = { path = "../../lib" }
creusot-contracts = { git = "https://github.com/cmester0/creusot", branch = "add_default_to_vec" } # branch = "master"

[features]
hacspec = []
# use_attributes = ["hacspec-attributes", "hacspec-attributes/print_attributes"]
contracts = ["creusot-contracts/contracts"]

[dev-dependencies]
hacspec-dev = { path = "../../utils/dev" }
criterion = "0.4"
rand = "0.8"